import { ethers } from "ethers";
import fs from "fs";
import path from "path";
import dotenv from "dotenv";

dotenv.config();

// ✅ Load ABI + contract address generated by deploy.js
const blueCarbonPath = path.resolve("./abi/BlueCarbon.json");
const blueCarbonJson = JSON.parse(fs.readFileSync(blueCarbonPath, "utf-8"));

const provider = new ethers.JsonRpcProvider(process.env.SEPOLIA_URL);

// ⚠️ Backend is using server signer (private key in .env)
const wallet = new ethers.Wallet(process.env.PRIVATE_KEY, provider);

// ✅ Contract instance
const blueCarbonContract = new ethers.Contract(
  blueCarbonJson.address,
  blueCarbonJson.abi,
  wallet
);

console.log("🔗 Connected to BlueCarbon at:", blueCarbonJson.address);

export { provider, wallet, blueCarbonContract };
